### ISSUE TITLE
should client_max_body_size get increased ?

### ISSUE THREAD

**Issue by n00dl3** [YunoHost-Apps/gogs_ynh_old#21]
I don't know if it's a good idea, at least in a security point of view.
There is an ssh access for large commit, but if a firewall is a bit restrictive, it would be nice if you could push more than the nginx's default (1MB) via https.
Maybe letting the user choose at install time would be nice...

**Comment by mbugeia** [comment]
Yes that's a good idea ; client_max_body_size don't cause any security issue AFAIK so it shoud be increased.

**Comment by n00dl3** [comment]
I think it could open the gate to DDoS issues if the limit is too high, and I know that's why the sysadmin at my work is limiting this kind of things. For example, say there are 100 concurrent requests:
100 x 1MB = 100MB of RAM
100 x 10MB = 1GB of RAM
So, as Yunohost can be install on a Raspberry, this could be an issue. That's why I think we should ask the administrator when he installs the app.
However, I'm not a sysadmin expert...

**Comment by mbugeia** [comment]
Well I understand but with the current implementation of gogs the only authorized users are yunohost users. To upload anything you must be logged so you have to trust your yunohost user like in most apps, so it's not a problem for me. 

BTW I don't think yunohost have any kind of protection over DDoS since it's not designed to host high traffic app/website.

**Comment by stevenroose** [comment]
The fact that Yunohost servers have no DDoS protection is an argument to be
cautious, right? Since a lot of users will somehow have to reveal their
hosts location, it is possible that they will be subject to an attack and
since they are unprotected, they are very vulnerable.

I'd suggest to not increase the limit by default but give the user the
possibility to do so. When implementing this, don't forget to check the
current value of the limit, because if another app already increased it to
a higher value, we might end up decreasing it instead.

**Comment by mbugeia** [comment]
I don't want to let the user choice for something like this, it complexify the script for nothing. Plus is the way others yunohost app works, it's an implementation of an app with a reasonable default configuration. For a git service something like 50 or 100Mo seems reasonable.

The DDoS discussion is for me very irrelevant on yunohost, if you are subject to a DDoS you certainly have other problem than gogs upload limit by your own users. Checking the other app limit is useless since the parameter is set for a specific location.

**Comment by n00dl3** [comment]
@stevenroose as mbugeia said, you can set the limit for a specific location. 

However @mbugeia, even if only the ynh users have enough rights to push to the repo, we are talking about nginx limit, not gogs one. So, even if the request returns a 40\* error (method not allowed or whatever), the request's content will be held in memory by nginx while it does not return gogs output. IMHO 50 to 100MB is **really** too high.

BTW it seems apache's default is 4MB.

**Comment by mbugeia** [comment]
@n00dl3 I understand but I don't think 50MB is too high (maybe 100MB is), it seems reasonable to have a repository that contain a binary file of this size. And as I said I don't think protecting for DDoS on a personal server makes much sense. Who want to DDoS a server that affect 1-10 people ? If you really want to protect your app the solution is to not make the app public.
Also most official yunohost app have a client_max_body_size of 10G so you may want to discuss this on the forum.

**Comment by n00dl3** [comment]
> so you may want to discuss this on the forum

Actually I don't really care about `client_max_body_size` to be very high for my own use case. I suggested the idea, so I'm glad if you integrate it. I just wanted to point out that it does have some kind of security implications, and as I don't know Yunohost policy about this kind of thing, I thought it was worth to notice it...

**Comment by mbugeia** [comment]
Yes, I agree and appreciate that you point out possible security implications that I did not think about. I argue just that in this case for me it is not very relevant to protect against a DDoS attack.

I will try to update gogs very soon with this and a new gogs version (with PR support \o/).

**Comment by mbugeia** [comment]
@n00dl3 @stevenroose I've updated Gogs in Dev branch if you want to betatest it https://github.com/mbugeia/gogs_ynh/tree/dev instruction are on the readme

**Comment by stevenroose** [comment]
@mbugeia I lost track on my PRs. What were the reasons why they were not yet merged?
The one still has an error I should resolve, but the installation path migration can be merged.

Can I contact you somewhere? I don't seem to find an e-mail address or anything.
