### ISSUE TITLE
adduser --disabled-login can prevent ssh access

### ISSUE THREAD

**Issue by julienmalik** [YunoHost-Apps/gogs_ynh_old#32]
On my install I needed to enable "UsePAM yes" in my SSH config to be able to push/pull via ssh.
I suspect this comes from the  --disabled-login switch.

The error I got from ssh server were : 

```
Feb 10 11:52:35 ynh sshd[17386]: User gogs not allowed because account is locked
Feb 10 11:52:35 ynh sshd[17386]: input_userauth_request: invalid user gogs [preauth
```

**Comment by mbugeia** [comment]
I think I just need to add to the readme that "UsePAM yes" in SSH config is needed to push/pull via ssh.

Removing --disabled-login won't change this behaviour, will-it ?

**Comment by julienmalik** [comment]
well I have no problem to ssh as admin with "UsePAM no", that's why I thought it comes from it. But you're right I need to test further.

**Comment by mbugeia** [comment]
I think admin works because it's a LDAP user, not true PAM. I will test it. Either way this need to be documented.

**Comment by mbugeia** [comment]
It seems that you were right about --disabled-login, it appears to lock the user ('!' in /etc/shadow).

I fixed it and added a note about the correct sshd configuration. I'm not using UsePAM yes since it seems to work but cause timeout during my test. 

https://github.com/YunoHost-Apps/gogs_ynh/commit/7133f1a14c540d7619022718d1d33e4ff5db0bae
