### ISSUE TITLE
Start Gogs after Nginx

### ISSUE THREAD

**Issue by ghost** [YunoHost-Apps/gogs_ynh_old#39]
Hello,
Thanks for this package.

Many times after restarting my server, Gogs doesn't work with an 502 HTTP error, because it is proxied by Nginx.
Adding in gogs.service "After=nginx.service" after "After=slapd.service" prevent this issue.

Best regard

**Comment by mbugeia** [comment]
Hi,
Are you sure this prevent the issue ? AFAIK gogs doesn't need nginx to start. And it's probably nginx that gives you a 502 error, not gogs.

**Comment by ghost** [comment]
Hi,
Yes, it is. Nginx gives the 502 error.
I am not totally sure, but I made this change today morning and restarted my server 3 times today and I have not that error any more. Before that I had that error after every reboot.

**Comment by mbugeia** [comment]
Well I think that's not the way it works, gogs really don't need nginx to start. Proof is you can stop nginx ang gogs is still working locally:

```
16:30 root@max ~ # curl http://localhost:6000
<a href="/explore">Found</a>.

16:30 root@max ~ # systemctl stop nginx.service                 
16:31 root@max ~ # curl http://localhost:6000  
<a href="/explore">Found</a>.
```

Nginx here is just binding the port 6000 to https://yourdomain.tld/gogspath
I don't really mind making this little change but IMHO it's not necessary and your issue is elsewhere, by the way my gogs start just fine at boot without it.
