### ISSUE TITLE
Delete history to remove source archives

### ISSUE THREAD

**Issue by stevenroose** [YunoHost-Apps/gogs_ynh_old#40]
To solve #29, I implemented install from GitHub archive and deleted the GitHub history. You can see the result in [my master](https://github.com/stevenroose/gogs_ynh).

To see the changes that I made, check out this commit: https://github.com/stevenroose/gogs_ynh/commit/b1edc78b85881058c17d162eda5cd710843a9777

I tested the `do_install` script on my computer, but I could not test the whole package because I don't have a test environment for YunoHost (using an old pc because main is broken). So can someone test it for me?

After testing, in order to upgrade this package to the new history, do the following:

``` bash
git remote add stevenroose https://github.com/stevenroose/gogs_ynh
git fetch stevenroose
git checkout master
git reset --hard stevenroose/master
git push -f origin master
```

I want to get Gogs installed on my machine asap, so I will try to fix as much as possible of the open issues for the Official Release milestone as I can.

**Comment by mbugeia** [comment]
Hi, great work! Unfortunatly it doesn't work:
- do_install 0 /opt/gogs
  Warning: ./install: line 55: do_install: command not found

**Comment by stevenroose** [comment]
whoops, can you try with ./do_install? Or perhaps the file needs the
executable flag?

**Comment by stevenroose** [comment]
@mbugeia Could you perhaps try to resolves the problems in this change? Check out this commit https://github.com/stevenroose/gogs_ynh/commit/607a5ac8daa5470d0890a281d3c86e0d4c62ff70 for the latest changes in my master branch.

Since I cannot test myself either someone else has to do it, or we wait until I have a new computer and that can take a while :D

**Comment by M5oul** [comment]
@stevenroose,

### Dev env

You really should test your code.
You could easily install a dev environement with [ynh-dev](https://github.com/YunoHost/ynh-dev), which works very well.

### Issues
- I solved previous issue with:

``` bash
sudo bash do_install 0 $install_path
```
- I tried with version `0.9.48`.
- I needed to add [extra swap](https://github.com/YunoHost-Apps/searx_ynh/blob/master/scripts/install#L35-L50) on a 512 ram VM to build Gogs.
- A [`$` is missing](https://github.com/stevenroose/gogs_ynh/blob/master/scripts/do_install#L39).
- A [`sudo` is missing](https://github.com/stevenroose/gogs_ynh/blob/master/scripts/install#L56)

#### MySQL database issue
- Finally, there is no database table:

``` bash
+ sleep 30
+ sudo sed -i s@yuno_admin@moul@g ../conf/login_source.sql
++ sudo cat /etc/yunohost/mysql
+ mysql -u root '-px0Dv[mfogJ'
Warning: ERROR 1146 (42S02) at line 1: Table 'gogs.login_source' doesn't exist
Executing script '/var/cache/yunohost/from_file/scripts/remove'...
```

MySQL database was well created:

``` bash
+ sudo yunohost app initdb gogs -p <password>
Warning: 'yunohost app initdb' is deprecated and will be removed in the future
The MySQL database has been initialized
+ sudo yunohost app setting gogs mysqlpwd -v <password>
```

May be this `conf/login_source.sql` is no more compatible with the version I have tested?

I also tried to do make `sleep` the script `90s`, and didn't works.

Our previous version was 0.8.10, now 0.9.48. Six versions happen between, Things could have changed with SQL.

I don't see any [modification about LDAP authentication since this release](https://github.com/gogits/docs/commits/master/en-US/features/authentication.md).

I put an `exit 0` [before mysql modification](https://github.com/stevenroose/gogs_ynh/blob/master/scripts/install#L107).
In PhpMyAdmin, I get `No tables found in database.` for `gogs` database.

It seem that the issue come from my MySQL database which was corrupted.

### Work on the same repository

As @stevenroose enhance the package on his [repository](https://github.com/stevenroose/gogs_ynh) trying to reduce the size.
It's annoying to have many repositories.
I don't know if you could do this commands on this repository on an other branch.
If so, it would be great to do it here, that way we could contribute on your branch.

I tested it on two dev env.

### \o/ YoloHost \o/

I really want to have a Gogs package working on YunoHost 2.4 with last Gogs version.

**Comment by mbugeia** [comment]
@M5oul I'll try to update the package soon using all the new shiny yunohost helpers of v2.4. I will use some code of @stevenroose and probably rewrite the git history too to reduce the package size.

I have a little more experience with gogs now since I've deployed it at my work. I use docker and fpm to build a debian package of compiled sources but the principles are the same. All updates (database included) have happened without a hitch.

**Comment by M5oul** [comment]
Cool!

**Comment by mbugeia** [comment]
Fixed on the new repo https://github.com/YunoHost-Apps/gogs_ynh
