### ISSUE TITLE
User creation forgotten in install script

### ISSUE THREAD

**Issue by stevenroose** [YunoHost-Apps/gogs_ynh_old#6]
It seems weird that noone noticed this, so I think maybe the gogs user is created by one of the yunohost calls.

But here in the install script
https://github.com/mbugeia/gogs_ynh/blob/master/scripts/install#L33
The gogs user is mentioned before it is created.

**Comment by mbugeia** [comment]
The user is created by the deb package so it's not an issue. BTW don't use this package, it's broken right now.

**Comment by stevenroose** [comment]
I wasnt planning to use it until LDAP integration works, but I was
considering to try to fix that myself. How comes its broken?

**Comment by mbugeia** [comment]
Well don't remember exactly what's broken but I use the debian package https://packager.io/gh/pkgr/gogs and an update broke it. Since it's written in Go I think it's better to use binary with yunohost because there is no risk to broke it with an update. Moreover IMHO the debian package is not very good, for example it create 3 service instead of one...

I've done some work for this, you can look at the unstable branche but it's not functionnal yet. Init script don't work (maybe this PR will correct it https://github.com/gogits/gogs/pull/1274). Unfortunatly I will not have time to work on it until july so if you want to fork/improve it, it would be appreciated.

**Comment by stevenroose** [comment]
Whats the benefit of a deb package over just installing Go and registering
a service manually that runs the Go executable?

**Comment by mbugeia** [comment]
None except easier installation and easier update (in theory). That's why I want to switch to binary.

**Comment by stevenroose** [comment]
The upgrade script could just pull the latest stable from GitHub and
compile. Well, I'm installing a YunoHost in August, perhaps I'll take a
look at Gogs and update this script to work with LDAP and binaries.
