### ISSUE TITLE
502 Bad Gateway (debian jessie)

### ISSUE THREAD

**Issue by Shnoulle** [YunoHost-Apps/gogs_ynh_old#9]
With Debian 8, on subdirectory : 502 Bad Gateway

In log:

```
2015/06/02 13:00:15 [error] 23757#0: *115673 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.254, server: gogs.example.net, request: "GET /gogs/ HTTP/1.1", upstream: "http://127.0.0.1:6000/", host: "gogs.example.net"
2015/06/02 13:00:15 [error] 23757#0: *115673 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.254, server: gogs.example.net, request: "GET /gogs/ HTTP/1.1", upstream: "http://[::1]:6000/", host: "gogs.example.net"
```

**Comment by mbugeia** [comment]
Should be fixed with #10

**Comment by Oliquae** [comment]
I actually have this issue on the same system. As it's not marked as resolved, I post the log here : 
`2015/11/15 22:42:51 [error] 19340#0: *2488 connect() failed (111: Connection refused) while connecting to upstream, client: 2a0:a03f:c76:d80:ea2a:eaff:fe3a9c3, server: git.hiserver.tld, request: "GET /_/ HTTP/1.1", upstream: "http://[::1]:6000/", host: "git.hiserver.tld", referrer: "https://hiserver.tld/yunohost/admin/"`

In anytime, even if I reinstall the app, I have the very same error: `502 - bad gateway`
Is there a fix before an update ?

**Comment by mbugeia** [comment]
This issue refer to an old version of the package so it's probably a different 502 error ;) This is a generic server side error and most of the times it happens when the app is not started.

Anyway, did you try to start the service manually with systemctl restart gogs.service ?

It seems that sometimes at computer restart the service does not start properly. You can also look at gogs's log in /var/log/gogs and with journalctl -u gogs to see if there is something interesting. I do not have time to look into this this week but please keep me in touch with your investigations.

**Comment by Oliquae** [comment]
Okay then. I'll make another issue. Then it'll be clearer.
